# ============================================================================
# Handlers du rôle logstash
# ============================================================================
---
- name: Redémarrer Logstash
  ansible.builtin.systemd:
    name: logstash
    state: restarted
