# ============================================================================
# Variables communes à TOUS les nœuds Elasticsearch (master, data, coord)
# ============================================================================
es_http_port: 9200
es_transport_port: 9300
