# ============================================================================
# Variables spécifiques aux nœuds Data Elasticsearch
# ============================================================================
es_node_roles: '["data_hot"]'
es_heap_size: "3g"   # 50% de 6 GB RAM
