# ============================================================================
# Variables spécifiques aux nœuds Master Elasticsearch
# ============================================================================
es_node_roles: '["master"]'
es_heap_size: "2g"   # 50% de 4 GB RAM
