# ============================================================================
# Variables Filebeat - Déployé sur tous les nœuds (14 VMs)
# ============================================================================
filebeat_version: "{{ elastic_version }}"
