# ============================================================================
# Variables Heartbeat - Déployé sur lb-01 et lb-02 uniquement
# ============================================================================
heartbeat_version: "{{ elastic_version }}"
