# ============================================================================
# Handlers du rôle filebeat
# ============================================================================
---
- name: Redémarrer Filebeat
  ansible.builtin.systemd:
    name: filebeat
    state: restarted
