# ============================================================================
# Variables du rôle logstash
# ============================================================================
logstash_certs_dir: "/etc/logstash/certs"
logstash_beats_port: 5044
