# ============================================================================
# Handlers du rôle kibana
# ============================================================================
---
- name: Redémarrer Kibana
  ansible.builtin.systemd:
    name: kibana
    state: restarted
