# ============================================================================
# Variables du rôle kibana
# ============================================================================
kibana_certs_dir: "/etc/kibana/certs"
