# ============================================================================
# Variables du rôle alerting
# ============================================================================
alert_check_interval: "1m"
alert_ssh_threshold: 10
alert_cpu_threshold: 90
